### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ronaldohornburgembraco** [zetatul/WPFLern#1]
Hello,

Hope everything is alright with you.

I've seen you registered the organization "embraco" in github. Are you using it? The company I work for is also named Embraco, and we would like to use this as our organization name for our repositories. In case you are not using this account, would you be willing to release or change its name? Thank you very much!

**Comment by zetatul** [comment]
Здравствуйте.
Простите плохо владею английским. Вашу просьбу понял, имя сменил, надеюсь Вам это поможет.
Удачи Вам.

**Comment by ronaldohornburgembraco** [comment]
Отлично, Спасибо!
